# Washer
sensor:
- platform: template
  sensors:
     washer_time_display:
       friendly_name: "Washer Time Display"
       value_template: >
         {% if is_state('sensor.washing_machine', 'unavailable') %}
         {% elif is_state('sensor.washing_machine', 'Finished') %}
         {% elif is_state('sensor.washing_machine', 'Idle') %}

         {% else %}
         {{ state_attr('sensor.washing_machine', 'remaining_minutes') }}
         {% endif %}

     blank:
       friendly_name: "Blank Sensor"
       value_template: ""
- platform: template
  sensors:
     washer_program:
       friendly_name: "Washer Program"
       value_template: >
         {{ state_attr('sensor.washing_machine', 'program') }}
- platform: template
  sensors:
     washer_spin_speed:
       friendly_name: "Washer Spin Speed"
       value_template: >
         {% if is_state('sensor.washing_machine', 'unavailable') %}
         {% elif is_state('sensor.washing_machine', 'Idle') %}
         
         {% else %}
         {{ state_attr('sensor.washing_machine', 'spin_speed') }}
         {% endif %}
- platform: template
  sensors:
     washer_temperature:
       friendly_name: "Washer Temperature"
       value_template: >
         {% if is_state('sensor.washing_machine', 'unavailable') %}
         {% elif is_state('sensor.washing_machine', 'Idle') %}
         
         {% else %}
         {{ state_attr('sensor.washing_machine', 'temperature') }}
         {% endif %}
