# Washer Template Sensors
sensor:
- platform: template
  sensors:
     washer_time_display:
       friendly_name: "Washer Time Display"
       icon_template: mdi:progress-clock
       value_template: >
         {% if is_state('sensor.washing_machine', 'unavailable') %}
         {% elif is_state('sensor.washing_machine', 'Idle') %}

         {% elif is_state('sensor.washing_machine', 'Finished') %}
         FINISH
         {% elif is_state('sensor.washing_machine', 'Error') %}
         Error
         {% else %}
         {% set time = state_attr('sensor.washing_machine', 'remaining_minutes') | int %}
         {% if time >= 60 %}{{ time // 60 }}:{{ '{:0>2d}'.format(time%60) }} {% elif time < 10 %} {{ 0 }}:{{ 0 }}{{time}} {% else %} {{ 0 }}:{{time}} {% endif %}
         {% endif %}
- platform: template
  sensors:
     washer_program:
       friendly_name: "Washer Program"
       icon_template: mdi:tune
       value_template: >
         {{ state_attr('sensor.washing_machine', 'program') }}
- platform: template
  sensors:
     washer_spin_speed:
       friendly_name: "Washer Spin Speed"
       icon_template: mdi:rotate-right
       value_template: >
         {% if is_state('sensor.washing_machine', 'unavailable') %}
         {% elif is_state('sensor.washing_machine', 'Idle') %}
         
         {% else %}
         {{ state_attr('sensor.washing_machine', 'spin_speed') }}
         {% endif %}
- platform: template
  sensors:
     washer_temperature:
       friendly_name: "Washer Temperature"
       icon_template: mdi:thermometer
       value_template: >
         {% if is_state('sensor.washing_machine', 'unavailable') %}
         {% elif is_state('sensor.washing_machine', 'Idle') %}
         
         {% else %}
         {{ state_attr('sensor.washing_machine', 'temperature') }}
         {% endif %}
